# ai_agent.R
library(R6)
library(stringr) # For text extraction
library(glue)    # For easy string formatting in the report

PathologyAIAgent <- R6Class("PathologyAIAgent",
                            public = list(
                              
                              summarize_ehr_data = function(ehr_text) {
                                cat("\n[AI Agent] Starting EHR summarization...\n")
                                
                                # Use stringr to find key information 
                                psa_match <- str_extract(ehr_text, "(?i)PSA.*?([0-9.]+)\\s*ng/mL")
                                psa_value <- str_extract(psa_match, "[0-9.]+")
                                
                                family_hx_match <- str_extract(ehr_text, "Family History: .*?\\.")
                                
                                summary_points <- c()
                                if (!is.na(psa_value)) {
                                  summary_points <- c(summary_points, glue("Relevant Labs: Elevated PSA of {psa_value} ng/mL."))
                                }
                                if (!is.na(family_hx_match)) {
                                  summary_points <- c(summary_points, glue("Relevant History: {str_remove(family_hx_match, 'Family History: ')}"))
                                }
                                
                                cat("[AI Agent] EHR summarization complete.\n")
                                if (length(summary_points) > 0) {
                                  return(paste(summary_points, collapse = "\n"))
                                } else {
                                  return("No key information automatically extracted.")
                                }
                              },
                              
                              analyze_slide_image = function(specimen_type) {
                                cat("\n[AI Agent] Starting simulated slide analysis...\n")
                                
                                # Using a named list
                                findings <- list()
                                if (str_detect(tolower(specimen_type), "prostate")) {
                                  findings <- list(
                                    "Pattern Identification" = "Acinar proliferation identified.",
                                    "Gleason Score (AI Suggestion)" = "3+4=7 (Grade Group 2)",
                                    "Tumor Quantification" = "Tumor involves 3 of 12 cores, 40% of positive core length.",
                                    "Perineural Invasion" = "Identified.",
                                    "Lymphovascular Invasion" = "Not identified."
                                  )
                                } else {
                                  findings <- list("Analysis" = "No specialized analysis model for this specimen type.")
                                }
                                
                                cat("[AI Agent] Simulated analysis complete.\n")
                                return(findings)
                              },
                              
                              draft_report = function(specimen, clinical_summary, ai_findings) {
                                cat("\n[AI Agent] Drafting pathology report...\n")
                                
                                # Use glue package for easy-to-read templating
                                findings_text <- ""
                                for (name in names(ai_findings)) {
                                  findings_text <- paste0(findings_text, glue("- {name}: {ai_findings[[name]]}\n"))
                                }
                                
                                report <- glue(
                                  "--- DRAFT PATHOLOGY REPORT (Generated by AI Agent) ---
        
        Patient ID:         {specimen$patient_id}
        Specimen ID:        {specimen$specimen_id}
        Specimen Type:      {specimen$specimen_type}
        Received Date:      {format(specimen$received_time, '%Y-%m-%d %H:%M')}

        AI-GENERATED CLINICAL SUMMARY:
        ------------------------------
        {clinical_summary}

        AI-ASSISTED MICROSCOPIC ANALYSIS:
        ---------------------------------
        {findings_text}
        AI-SUGGESTED DIAGNOSIS:
        -----------------------
        Prostatic adenocarcinoma, Gleason Score 7 (3+4), Grade Group 2.
        (See detailed findings above).

        *** NOTE: This is an AI-generated draft. All findings and diagnoses require final review, 
        verification, and sign-out by a qualified pathologist. ***
      ")
                                
                                cat("[AI Agent] Report draft complete.\n")
                                return(report)
                              }
                            )
)