# main.R

# Load the class definitions from the other files
source("data_models.R")
source("simulated_systems.R")
source("ai_agent.R")

run_workflow <- function() {
  cat("--- Starting Pathology Workflow Simulation ---\n")
  
  # 1. Initialize systems
  ehr_system <- MockEHRSystem$new()
  lis_system <- MockLIS$new()
  ai_agent <- PathologyAIAgent$new()
  
  # 2. Specimen arrives (instantiate the R6 object)
  specimen <- Specimen$new(
    specimen_id = "S2025-P451",
    patient_id = "P12345",
    specimen_type = "Prostate Core Biopsy"
  )
  lis_system$log_event(specimen$specimen_id, paste("Specimen received for patient", specimen$patient_id))
  
  # --- AI AGENT INTERVENTION ---
  
  # 3. Agent pulls and summarizes EHR data
  specimen$update_status("AI Analysis: Summarizing History")
  raw_history <- ehr_system$get_patient_history(specimen$patient_id)
  specimen$clinical_summary <- ai_agent$summarize_ehr_data(raw_history)
  lis_system$log_event(specimen$specimen_id, "EHR clinical summary generated by AI.")
  
  cat("\n--- AI-Generated Clinical Summary ---\n")
  cat(specimen$clinical_summary)
  cat("\n-----------------------------------\n")
  
  # 4. Agent "analyzes" the slide
  specimen$update_status("AI Analysis: Analyzing Image")
  specimen$ai_image_findings <- ai_agent$analyze_slide_image(specimen$specimen_type)
  lis_system$log_event(specimen$specimen_id, "AI slide analysis complete.")
  
  cat("\n--- AI-Generated Image Findings ---\n")
  for(name in names(specimen$ai_image_findings)) {
    cat(sprintf("- %s: %s\n", name, specimen$ai_image_findings[[name]]))
  }
  cat("---------------------------------\n")
  
  # 5. Agent drafts the report
  specimen$update_status("AI Analysis: Drafting Report")
  specimen$draft_report <- ai_agent$draft_report(
    specimen,
    specimen$clinical_summary,
    specimen$ai_image_findings
  )
  lis_system$log_event(specimen$specimen_id, "Initial report drafted by AI.")
  
  # 6. Final Report is ready for pathologist review
  specimen$update_status("Pending Pathologist Final Review")
  cat("\n\n#################################################################\n")
  cat("## Final AI-Drafted Report for Pathologist Review\n")
  cat("#################################################################\n")
  cat(specimen$draft_report)
  cat("\n--- End of Simulation ---\n")
}

# Run the main function
run_workflow()